-- Create catalog table
create table catalog (
  id          bigint generated by default as identity primary key,
  supplier_id bigint not null references partners(id) on delete cascade,
  variety     text not null,
  color       text not null default '',
  stems       text not null default '',
  price       text not null default '',
  notes       text not null default ''
);

alter table catalog enable row level security;

create policy "allow select" on catalog for select to authenticated
  using (auth.jwt()->>'email' = 'meg@poppyflowers.com');
create policy "allow insert" on catalog for insert to authenticated
  with check (auth.jwt()->>'email' = 'meg@poppyflowers.com');
create policy "allow update" on catalog for update to authenticated
  using  (auth.jwt()->>'email' = 'meg@poppyflowers.com')
  with check (auth.jwt()->>'email' = 'meg@poppyflowers.com');
create policy "allow delete" on catalog for delete to authenticated
  using (auth.jwt()->>'email' = 'meg@poppyflowers.com');

-- Tighten existing partners policies to meg@ only
drop policy "allow select" on partners;
drop policy "allow insert" on partners;
drop policy "allow update" on partners;

create policy "allow select" on partners for select to authenticated
  using (auth.jwt()->>'email' = 'meg@poppyflowers.com');
create policy "allow insert" on partners for insert to authenticated
  with check (auth.jwt()->>'email' = 'meg@poppyflowers.com');
create policy "allow update" on partners for update to authenticated
  using  (auth.jwt()->>'email' = 'meg@poppyflowers.com')
  with check (auth.jwt()->>'email' = 'meg@poppyflowers.com');
