CREATE TABLE "supplierCatalogs" (
  id bigint generated by default as identity primary key,
  "supplierId" bigint not null references suppliers(id) on delete cascade,
  label text not null default '',
  url text not null,
  type text not null check (type in ('link', 'pdf'))
);
ALTER TABLE "supplierCatalogs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow select" ON "supplierCatalogs" FOR SELECT TO authenticated
  USING (auth.jwt()->>'email' ILIKE '%@poppyflowers.com');
CREATE POLICY "allow insert" ON "supplierCatalogs" FOR INSERT TO authenticated
  WITH CHECK (auth.jwt()->>'email' = 'meg@poppyflowers.com');
CREATE POLICY "allow delete" ON "supplierCatalogs" FOR DELETE TO authenticated
  USING (auth.jwt()->>'email' = 'meg@poppyflowers.com');

-- Storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('supplier-catalogs', 'supplier-catalogs', false);
CREATE POLICY "supplier-catalogs allow read" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'supplier-catalogs' AND auth.jwt()->>'email' ILIKE '%@poppyflowers.com');
CREATE POLICY "supplier-catalogs allow insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'supplier-catalogs' AND auth.jwt()->>'email' = 'meg@poppyflowers.com');
CREATE POLICY "supplier-catalogs allow delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'supplier-catalogs' AND auth.jwt()->>'email' = 'meg@poppyflowers.com');
